import { execFile } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { getGlobalConfigPath } from "./config-store.js";

// 登录自启动（仅 Windows）：HKCU Run 键指向 wscript.exe 隐藏执行 autostart.vbs。
// 不再把 node.exe 路径直接写进注册表：
// 1. fnm/nvm 等版本管理器的安装路径随版本变化（fnm\node-versions\v22.22.3\...），升级即失效；
//    VBS 运行时优先解析 fnm 默认别名（aliases\default，升级后指向不变）。
// 2. node 是控制台程序，被 Run 键直接拉起会在登录时弹出终端窗口（wscript 为 GUI 子系统，
//    完全无窗口），该窗口一旦被用户关闭 daemon 随之退出，表现为"开机后 web 访问不到"。
const RUN_KEY = "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run";
const VALUE_NAME = "SshMcpServer";

function reg(args: string[]): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    execFile("reg.exe", args, { windowsHide: true }, (err, stdout, stderr) => {
      resolve({ code: err ? (err as any).code ?? 1 : 0, stdout: String(stdout || ""), stderr: String(stderr || "") });
    });
  });
}

export function isAutostartSupported(): boolean {
  return process.platform === "win32";
}

/** VBS 启动器落盘位置（用户级目录，与 HKCU 注册表键同一权限层级，无需管理员） */
export function getAutostartVbsPath(): string {
  const base = process.env.LOCALAPPDATA || path.join(os.homedir(), "AppData", "Local");
  return path.join(base, "SshMcpServer", "autostart.vbs");
}

/**
 * 自启拉起链路的输出日志（独立文件，不能复用 daemon.log）：
 * cmd 的 >> 重定向以严格共享模式打开目标文件，而 daemon.log 被常驻进程的
 * stdout 句柄长期持有（Node 全共享模式打开），cmd 追加会 sharing violation
 * 且隐藏窗口下报错不可见，表现为整条启动命令静默不执行。
 */
function getAutostartLogPath(): string {
  return path.join(path.dirname(getGlobalConfigPath()), "autostart.log");
}

/**
 * 会话级/缓存级临时路径：随 shell 会话结束或 npm 清缓存而销毁，
 * 写入自启注册表必然失效，启用前必须拒绝。
 */
export function isUnstableEntryScript(scriptPath: string): boolean {
  const normalized = scriptPath.replace(/\//g, "\\").toLowerCase();
  return normalized.includes("fnm_multishells") || normalized.includes("\\_npx\\");
}

/** 解析启用自启时的稳定入口脚本：argv[1] 绝对化 + realpath（剥掉会话级符号链接） */
function resolveEntryScript(override?: string): string {
  const raw = override ?? process.argv[1];
  if (!raw) throw new Error("无法定位入口脚本（argv[1] 为空），请改用 npm 安装后启用");
  let script = path.resolve(raw);
  try {
    script = fs.realpathSync(script);
  } catch {
    // realpath 失败保留原路径，由后续存在性/稳定性校验兜底
  }
  if (!fs.existsSync(script)) {
    throw new Error(`入口脚本不存在: ${script}`);
  }
  if (isUnstableEntryScript(script)) {
    throw new Error(
      "当前常驻服务运行自会话级临时目录（fnm multishell / npx 缓存），重启后路径即失效，" +
        "无法安全启用开机自启。请先执行: npm install -g @lzm04521/ssh-mcp-server",
    );
  }
  return script;
}

export interface AutostartVbsContext {
  /** 启用时的 node.exe 实路径，作为 fnm 默认别名缺失时的兜底快照 */
  fallbackNodeExe: string;
  /** 入口脚本稳定路径（如 npm 全局安装的 build/index.js） */
  scriptPath: string;
  /** daemon 输出日志路径 */
  logPath: string;
}

/**
 * 生成 autostart.vbs 内容（纯函数，导出供测试）。
 * 内容保持纯 ASCII：wscript 按本地代码页解析无 BOM 脚本，非 ASCII 注释可能乱码。
 * Windows 路径不可能含双引号，嵌入 VBS 字符串无需转义。
 * 日志必须是独立文件（autostart.log）：cmd 的 >> 打不开被常驻 daemon 持有的 daemon.log。
 */
export function buildAutostartVbs(ctx: AutostartVbsContext): string {
  return `' SSH MCP Server autostart launcher (generated by admin console, safe to delete)
' Starts the admin daemon with no console window at logon, appending output to autostart.log.
Option Explicit
Dim shell, fso, q, nodeExe, fnmAlias, cmdLine
Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
q = Chr(34)

' node preference: fnm default alias (survives node upgrades) > captured exe > PATH
nodeExe = ""
fnmAlias = shell.ExpandEnvironmentStrings("%APPDATA%") & "\\fnm\\aliases\\default\\node.exe"
If fso.FileExists(fnmAlias) Then nodeExe = fnmAlias
If nodeExe = "" And fso.FileExists("${ctx.fallbackNodeExe}") Then nodeExe = "${ctx.fallbackNodeExe}"
If nodeExe = "" Then nodeExe = "node"

cmdLine = q & nodeExe & q & " " & q & "${ctx.scriptPath}" & q & " --admin >> " & q & "${ctx.logPath}" & q & " 2>&1"
' cmd /d /s /c strips the outer quote pair and runs the inner line verbatim (redirect included)
shell.Run "cmd.exe /d /s /c " & q & cmdLine & q, 0, False
`;
}

/** 写入 VBS 启动器到用户目录 */
function writeAutostartVbs(ctx: AutostartVbsContext): string {
  const vbs = getAutostartVbsPath();
  fs.mkdirSync(path.dirname(vbs), { recursive: true });
  fs.writeFileSync(vbs, buildAutostartVbs(ctx), "utf-8");
  return vbs;
}

/** 注册表里写入的启动命令：wscript 隐藏执行 VBS 启动器（daemon 幂等启动，重复执行安全） */
export function buildAutostartCommand(): string {
  return `wscript.exe //B "${getAutostartVbsPath()}"`;
}

export async function getAutostartEnabled(): Promise<boolean> {
  if (!isAutostartSupported()) return false;
  const { code, stdout } = await reg(["query", RUN_KEY, "/v", VALUE_NAME]);
  return code === 0 && stdout.includes(VALUE_NAME);
}

/**
 * 开关登录自启。entryScript 可覆盖入口脚本（测试/迁移用），默认取当前进程 argv[1]。
 */
export async function setAutostart(enabled: boolean, opts: { entryScript?: string } = {}): Promise<boolean> {
  if (!isAutostartSupported()) {
    throw new Error("仅支持 Windows（写入 HKCU Run 注册表键）");
  }
  if (enabled) {
    const scriptPath = resolveEntryScript(opts.entryScript);
    let fallbackNodeExe = process.execPath;
    try {
      fallbackNodeExe = fs.realpathSync(fallbackNodeExe);
    } catch {
      // 解析失败（极端文件系统场景）保留原路径
    }
    writeAutostartVbs({ fallbackNodeExe, scriptPath, logPath: getAutostartLogPath() });
    const { code, stderr } = await reg([
      "add", RUN_KEY, "/v", VALUE_NAME, "/t", "REG_SZ", "/d", buildAutostartCommand(), "/f",
    ]);
    if (code !== 0) throw new Error(`写入注册表失败: ${stderr}`);
  } else {
    // 不存在时 reg delete 报错，属幂等删除，忽略
    await reg(["delete", RUN_KEY, "/v", VALUE_NAME, "/f"]);
    try {
      fs.rmSync(getAutostartVbsPath(), { force: true });
    } catch {
      // VBS 删除失败不影响自启关闭（注册表已清）
    }
  }
  return getAutostartEnabled();
}
